package org.textphone.launcher;

import static org.junit.Assert.*;
import android.Manifest;
import android.app.AlertDialog;
import android.app.AlarmManager;
import android.app.TimePickerDialog;
import android.content.Context;
import android.content.ContentProvider;
import android.content.ContentValues;
import android.content.Intent;
import android.content.pm.ProviderInfo;
import android.database.Cursor;
import android.database.MatrixCursor;
import android.net.Uri;
import android.os.Looper;
import android.provider.CalendarContract;
import android.provider.ContactsContract;
import android.view.View;
import android.widget.EditText;
import android.widget.TimePicker;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.TimeUnit;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.RuntimeEnvironment;
import org.robolectric.Shadows;
import org.robolectric.android.controller.ActivityController;
import org.robolectric.annotation.Config;
import org.robolectric.shadows.ShadowAlarmManager;
import org.robolectric.shadows.ShadowAlertDialog;
import org.robolectric.shadows.ShadowContentResolver;
import org.robolectric.shadows.ShadowDialog;
import org.robolectric.util.ReflectionHelpers;

@RunWith(RobolectricTestRunner.class)
@Config(sdk={23,35})
public class DailyPolishTest {
    private Context c;
    @Before public void clear(){c=RuntimeEnvironment.getApplication();for(String name:new String[]{"text_phone","pocket_agenda","pocket_planner","pocket_contact_draft","CalculatorActivity"})c.getSharedPreferences(name,0).edit().clear().commit();ClockStore.prefs(c).edit().clear().commit();ShadowAlarmManager.setCanScheduleExactAlarms(true);Shadows.shadowOf(RuntimeEnvironment.getApplication()).grantPermissions(Manifest.permission.POST_NOTIFICATIONS,Manifest.permission.READ_CONTACTS,Manifest.permission.WRITE_CONTACTS,Manifest.permission.READ_CALENDAR,Manifest.permission.WRITE_CALENDAR);}
    static void settle(PocketActivity activity)throws Exception{ExecutorService writes=ReflectionHelpers.getStaticField(PocketActivity.class,"WRITES");for(int i=0;i<4;i++){writes.submit(()->{}).get(5,TimeUnit.SECONDS);CameraAlbumTest.settle(activity);}}
    private static void click(PocketActivity a,String text){View view=PocketAppsTest.find(a.root,text);assertNotNull(text,view);assertTrue(view.performClick());Shadows.shadowOf(Looper.getMainLooper()).idle();}
    static void choose(String text){AlertDialog dialog=ShadowAlertDialog.getLatestAlertDialog();assertNotNull(dialog);for(int i=0;i<dialog.getListView().getAdapter().getCount();i++)if(text.equals(dialog.getListView().getAdapter().getItem(i).toString())){dialog.getListView().performItemClick(null,i,i);Shadows.shadowOf(Looper.getMainLooper()).idle();return;}fail("Missing choice: "+text);}
    @Test public void durationValidatesBeforeClosingAndSurvivesDraftResumeAndSave()throws Exception{
        ActivityController<AgendaActivity> controller=Robolectric.buildActivity(AgendaActivity.class).setup();try{AgendaActivity a=controller.get();click(a,"+ appointment");((EditText)a.body.findViewWithTag("appointment_title")).setText("Short planning session");a.body.findViewWithTag("appointment_duration").performClick();choose("Other duration");AlertDialog custom=ShadowAlertDialog.getLatestAlertDialog();EditText minutes=custom.findViewById(android.R.id.content).findViewWithTag("duration_minutes");minutes.setText("0");custom.getButton(AlertDialog.BUTTON_POSITIVE).performClick();assertTrue(custom.isShowing());assertNotNull(minutes.getError());minutes.setText("35");custom.getButton(AlertDialog.BUTTON_POSITIVE).performClick();assertFalse(custom.isShowing());a.onBackPressed();assertTrue(AgendaStore.list(c).isEmpty());assertEquals(35,AgendaDraft.read(c).event.minutes);click(a,"Continue draft");controller.recreate();a=controller.get();assertTrue(((android.widget.TextView)a.body.findViewWithTag("appointment_duration")).getText().toString().startsWith("Duration · 35 min"));click(a,"save");settle(a);assertEquals(1,AgendaStore.list(c).size());assertEquals(35,AgendaStore.list(c).get(0).minutes);assertNull(AgendaDraft.read(c));controller.recreate();assertNull(controller.get().body.findViewWithTag("appointment_title"));}finally{controller.pause().stop().destroy();}
    }
    @Test public void legacyAppointmentsStayOneHourAndInvalidDurationCannotChangeSavedData(){long now=System.currentTimeMillis();c.getSharedPreferences("pocket_agenda",0).edit().putString("events","[{\"id\":7,\"when\":"+now+",\"title\":\"Legacy\"}]").commit();AgendaStore.Event e=AgendaStore.find(c,7);assertEquals(60,e.minutes);assertEquals(now+3600000,e.end());e.minutes=1441;try{AgendaStore.save(c,e);fail();}catch(IllegalArgumentException expected){}assertEquals(60,AgendaStore.find(c,7).minutes);}
    @Test public void customDurationControlsOngoingFocusAndNativeCalendarEnd(){NativeDataTest.Provider provider=new NativeDataTest.Provider();ProviderInfo info=new ProviderInfo();info.authority="com.android.calendar";provider.attachInfo(c,info);ShadowContentResolver.registerProviderInternal(info.authority,provider);long now=System.currentTimeMillis();AgendaStore.Event e=new AgendaStore.Event();e.title="Long session";e.when=now-90*60000L;e.minutes=120;AgendaStore.save(c,e);assertEquals(e.id,DayPlan.local(c,now).next().id);assertEquals(now+30*60000L,DayPlan.local(c,now).next().end);c.getSharedPreferences("pocket_agenda",0).edit().putLong("google_calendar",7).commit();assertTrue(CalendarBridge.write(c,e));assertEquals(Long.valueOf(e.end()),provider.inserted.get(0).getAsLong(CalendarContract.Events.DTEND));e.minutes=15;AgendaStore.save(c,e);assertNull(DayPlan.local(c,now).next());}
    @Test public void editingAnAlarmReusesItsIdAndNewTimeAfterRecreation(){ClockStore.Entry e=new ClockStore.Entry();e.kind="alarm";e.title="Wake up";e.hour=7;e.minute=30;e.enabled=true;e.due=ClockStore.nextTime(7,30,System.currentTimeMillis());AlarmScheduler.saveAndArm(c,e);ActivityController<ClockActivity> controller=Robolectric.buildActivity(ClockActivity.class).setup();try{ClockActivity a=controller.get();a.body.findViewWithTag("clock_entry_"+e.id).performClick();((EditText)a.body.findViewWithTag("alarm_title")).setText("Train day");a.body.findViewWithTag("alarm_time").performClick();TimePickerDialog dialog=(TimePickerDialog)ShadowDialog.getLatestDialog();TimePicker picker=ReflectionHelpers.getField(dialog,"mTimePicker");picker.setHour(8);picker.setMinute(15);dialog.getButton(AlertDialog.BUTTON_POSITIVE).performClick();Shadows.shadowOf(Looper.getMainLooper()).idle();controller.recreate();a=controller.get();click(a,"save");ClockStore.Entry saved=ClockStore.find(c,e.id);assertEquals(1,ClockStore.entries(c).size());assertEquals("Train day",saved.title);assertEquals(8,saved.hour);assertEquals(15,saved.minute);assertEquals(1,Shadows.shadowOf(c.getSystemService(AlarmManager.class)).getScheduledAlarms().size());}finally{controller.pause().stop().destroy();}}
    @Test public void editingAnOffAlarmKeepsItOffWithoutDemandingExactAlarmAccess(){ClockStore.Entry e=new ClockStore.Entry();e.kind="alarm";e.title="Weekend";e.hour=9;e.minute=0;e.due=ClockStore.nextTime(9,0,System.currentTimeMillis());ClockStore.save(c,e);ShadowAlarmManager.setCanScheduleExactAlarms(false);ActivityController<ClockActivity> controller=Robolectric.buildActivity(ClockActivity.class).setup();try{ClockActivity a=controller.get();a.body.findViewWithTag("clock_entry_"+e.id).performClick();((EditText)a.body.findViewWithTag("alarm_title")).setText("Sunday");click(a,"save");assertFalse(ClockStore.find(c,e.id).enabled);assertEquals("Sunday",ClockStore.find(c,e.id).title);assertTrue(Shadows.shadowOf(c.getSystemService(AlarmManager.class)).getScheduledAlarms().isEmpty());assertNull(Shadows.shadowOf(a).getNextStartedActivity());}finally{controller.pause().stop().destroy();}}
    @Test public void timerPresetsAndLabelSurviveTabChangesAndRecreation(){ActivityController<ClockActivity> controller=Robolectric.buildActivity(ClockActivity.class).setup();try{ClockActivity a=controller.get();click(a,"timer");click(a,"50 min");((EditText)a.body.findViewWithTag("timer_label")).setText("Read chapter");click(a,"stopwatch");a.onBackPressed();assertEquals("50",((EditText)a.body.findViewWithTag("timer_minutes")).getText().toString());controller.recreate();a=controller.get();assertEquals("Read chapter",((EditText)a.body.findViewWithTag("timer_label")).getText().toString());click(a,"start timer");ClockStore.Entry timer=ClockStore.entries(c).get(0);assertEquals("Read chapter",timer.title);assertEquals("timer",timer.kind);assertTrue(ClockStore.remaining(c,timer)>=2999000);assertEquals(1,ClockStore.entries(c).size());}finally{controller.pause().stop().destroy();}}
    @Test public void calculatorStartsANewNumberAfterEqualsButChainsOperatorsAndCopiesExplicitly(){ActivityController<CalculatorActivity> controller=Robolectric.buildActivity(CalculatorActivity.class).setup();try{CalculatorActivity a=controller.get();((EditText)a.body.findViewWithTag("calculator_input")).setText("2+3");click(a,"=");controller.recreate();a=controller.get();click(a,"7");assertEquals("7",((EditText)a.body.findViewWithTag("calculator_input")).getText().toString());click(a,"+");click(a,"3");click(a,"=");click(a,"×");click(a,"2");click(a,"=");assertEquals("20",((EditText)a.body.findViewWithTag("calculator_input")).getText().toString());click(a,"copy");assertEquals("20",c.getSystemService(android.content.ClipboardManager.class).getPrimaryClip().getItemAt(0).getText().toString());click(a,"history");AlertDialog history=ShadowAlertDialog.getLatestAlertDialog();assertEquals("10×2 = 20",history.getListView().getAdapter().getItem(0));history.getListView().performItemClick(null,1,1);Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals("10",((EditText)a.body.findViewWithTag("calculator_input")).getText().toString());click(a,"4");assertEquals("4",((EditText)a.body.findViewWithTag("calculator_input")).getText().toString());}finally{controller.pause().stop().destroy();}}
    @Test public void invalidCalculationKeepsInputAndDoesNotAddHistory(){ActivityController<CalculatorActivity> controller=Robolectric.buildActivity(CalculatorActivity.class).setup();try{CalculatorActivity a=controller.get();EditText expression=a.body.findViewWithTag("calculator_input");expression.setText("8/0");click(a,"=");assertEquals("8/0",expression.getText().toString());assertEquals("[]",a.getPreferences(0).getString("history","[]"));assertNotNull(PocketAppsTest.find(a.root,"Cannot divide by zero."));}finally{controller.pause().stop().destroy();}}
    @Test public void plusInTheDialpadUsesTheCaretWithoutStartingACall(){ActivityController<PhoneActivity> controller=Robolectric.buildActivity(PhoneActivity.class,new Intent().putExtra("number","4930")).setup();try{PhoneActivity a=controller.get();EditText number=a.body.findViewWithTag("phone_number");number.setSelection(0);click(a,"+");assertEquals("+4930",number.getText().toString());assertTrue(Shadows.shadowOf(c.getSystemService(android.telecom.TelecomManager.class)).getAllOutgoingCalls().isEmpty());number.setSelection(1,3);click(a,"+");assertEquals("++30",number.getText().toString());}finally{controller.pause().stop().destroy();}}
    @Test public void messageAppChoicesOnlyOpenAnInstalledAppAfterATap(){android.content.pm.ResolveInfo info=new android.content.pm.ResolveInfo();info.activityInfo=new android.content.pm.ActivityInfo();info.activityInfo.name="Main";info.activityInfo.packageName="com.whatsapp";info.activityInfo.applicationInfo=new android.content.pm.ApplicationInfo();info.activityInfo.applicationInfo.packageName="com.whatsapp";Shadows.shadowOf(c.getPackageManager()).addResolveInfoForIntent(new Intent(Intent.ACTION_MAIN).addCategory(Intent.CATEGORY_LAUNCHER).setPackage("com.whatsapp"),info);ActivityController<ChatsActivity> controller=Robolectric.buildActivity(ChatsActivity.class).setup();try{ChatsActivity a=controller.get();assertNull(PocketAppsTest.find(a.body,"SMS inbox"));assertNotNull(a.root.findViewWithTag("chat_feed"));assertNull(Shadows.shadowOf(a).getNextStartedActivity());click(a,"Apps");choose("WhatsApp");assertEquals("com.whatsapp",Shadows.shadowOf(a).getNextStartedActivity().getComponent().getPackageName());click(a,"SMS inbox");assertEquals(MessagesActivity.class.getName(),Shadows.shadowOf(a).getNextStartedActivity().getComponent().getClassName());}finally{controller.pause().stop().destroy();}}
    @Test public void pinningAnOlderNoteMovesItFirstAndDoesNotAlterMarkdownOrDrafts(){PlannerStore store=new PlannerStore(c.getSharedPreferences("pocket_planner",0));long old=store.save(0,"note","# Trip\n- Train at 09:30"),newer=store.save(0,"note","# New note\nBody");store.draft("note",old,"# Unsaved trip\n- Camera");ActivityController<MainActivity> controller=Robolectric.buildActivity(MainActivity.class,new Intent().putExtra("pocket_screen","today")).setup();try{MainActivity a=controller.get();View root=a.findViewById(android.R.id.content);root.findViewWithTag("note_open_"+old).performLongClick();choose("Pin");root=a.findViewById(android.R.id.content);View first=root.findViewWithTag("note_open_"+old),second=root.findViewWithTag("note_open_"+newer);android.view.ViewGroup list=(android.view.ViewGroup)first.getParent();assertTrue(list.indexOfChild(first)<list.indexOfChild(second));assertTrue(store.notePinned(old));assertEquals("# Trip\n- Train at 09:30",store.find(old).text);assertEquals("# Unsaved trip\n- Camera",store.draft("note",old));controller.recreate();a=controller.get();a.findViewById(android.R.id.content).findViewWithTag("note_open_"+old).performClick();PocketAppsTest.find(a.findViewById(android.R.id.content),"Preview").performClick();PocketAppsTest.find(a.findViewById(android.R.id.content),"More").performClick();choose("Unpin");assertFalse(store.notePinned(old));assertEquals("# Unsaved trip\n- Camera",store.draft("note",old));store.pinNote(old,true);store.delete(old);assertFalse(store.notePinned(old));}finally{controller.pause().stop().destroy();}}
    private ContactsFixture contacts(){ContactsFixture provider=new ContactsFixture();ProviderInfo info=new ProviderInfo();info.authority=ContactsContract.AUTHORITY;provider.attachInfo(c,info);ShadowContentResolver.registerProviderInternal(info.authority,provider);return provider;}
    @Test public void contactAccessReturnAndDetailRecreationKeepTheAddressBookUsable()throws Exception{contacts();Shadows.shadowOf(RuntimeEnvironment.getApplication()).denyPermissions(Manifest.permission.READ_CONTACTS);ActivityController<ContactsActivity> controller=Robolectric.buildActivity(ContactsActivity.class).setup();try{ContactsActivity a=controller.get();assertNull(a.body.findViewWithTag("contact_search"));controller.pause();Shadows.shadowOf(RuntimeEnvironment.getApplication()).grantPermissions(Manifest.permission.READ_CONTACTS);controller.resume();settle(a);assertNotNull(a.body.findViewWithTag("contact_search"));click(a,"Ada");settle(a);assertNotNull(PocketAppsTest.find(a.body,"+49 30 5550100"));controller.recreate();a=controller.get();settle(a);assertNotNull(PocketAppsTest.find(a.body,"+49 30 5550100"));assertNull(a.body.findViewWithTag("contact_search"));}finally{controller.pause().stop().destroy();}}
    @Test public void contactEditDraftSurvivesBackAndRecreationWithoutWritingTheProvider()throws Exception{ContactsFixture provider=contacts();ActivityController<ContactsActivity> controller=Robolectric.buildActivity(ContactsActivity.class).setup();try{ContactsActivity a=controller.get();settle(a);click(a,"Ada");settle(a);click(a,"edit");((EditText)a.body.findViewWithTag("contact_name")).setText("Ada revised");controller.recreate();a=controller.get();a.onBackPressed();settle(a);assertEquals("Ada revised",ContactDraft.read(c).person.name);assertEquals(0,provider.writes);a.onBackPressed();settle(a);click(a,"Continue draft");settle(a);assertEquals("Ada revised",((EditText)a.body.findViewWithTag("contact_name")).getText().toString());click(a,"save");settle(a);assertEquals("Ada revised",provider.name);assertNull(ContactDraft.read(c));}finally{controller.pause().stop().destroy();}}
    @Test public void newContactDraftRequiresConfirmedDiscardAndFailedSaveRetainsIt()throws Exception{ContactsFixture provider=contacts();ActivityController<ContactsActivity> controller=Robolectric.buildActivity(ContactsActivity.class).setup();try{ContactsActivity a=controller.get();settle(a);click(a,"+ contact");((EditText)a.body.findViewWithTag("contact_name")).setText("Mira");((EditText)a.body.findViewWithTag("contact_phone")).setText("+4912345");a.onBackPressed();assertEquals("Mira",ContactDraft.read(c).person.name);assertEquals(0,provider.writes);click(a,"Continue draft");click(a,"Discard draft");AlertDialog confirm=ShadowAlertDialog.getLatestAlertDialog();confirm.getButton(AlertDialog.BUTTON_NEGATIVE).performClick();Shadows.shadowOf(Looper.getMainLooper()).idle();assertEquals("Mira",((EditText)a.body.findViewWithTag("contact_name")).getText().toString());provider.failWrites=true;click(a,"save");settle(a);assertNotNull(a.body.findViewWithTag("contact_name"));a.onBackPressed();assertEquals("Mira",ContactDraft.read(c).person.name);provider.failWrites=false;click(a,"Continue draft");click(a,"save");settle(a);assertNull(ContactDraft.read(c));assertEquals(1,provider.rawInserts);}finally{controller.pause().stop().destroy();}}
    @Test public void acceptedContactSaveAfterBackDoesNotReviveItsDraft()throws Exception{ContactsFixture provider=contacts();provider.entered=new java.util.concurrent.CountDownLatch(1);provider.release=new java.util.concurrent.CountDownLatch(1);ActivityController<ContactsActivity> controller=Robolectric.buildActivity(ContactsActivity.class).setup();try{ContactsActivity a=controller.get();settle(a);click(a,"+ contact");((EditText)a.body.findViewWithTag("contact_name")).setText("Mira");click(a,"save");assertTrue(provider.entered.await(5,TimeUnit.SECONDS));a.onBackPressed();assertNotNull(ContactDraft.read(c));provider.release.countDown();settle(a);assertNull(ContactDraft.read(c));assertEquals(1,provider.rawInserts);assertNotNull(a.body.findViewWithTag("contact_search"));}finally{provider.release.countDown();controller.pause().stop().destroy();}}
    @Test public void newerContactEditsSurviveADelayedAcceptedSaveAndReuseItsRawContact()throws Exception{ContactsFixture provider=contacts();provider.entered=new java.util.concurrent.CountDownLatch(1);provider.release=new java.util.concurrent.CountDownLatch(1);ActivityController<ContactsActivity> controller=Robolectric.buildActivity(ContactsActivity.class).setup();try{ContactsActivity a=controller.get();settle(a);click(a,"+ contact");((EditText)a.body.findViewWithTag("contact_name")).setText("Mira");click(a,"save");assertTrue(provider.entered.await(5,TimeUnit.SECONDS));((EditText)a.body.findViewWithTag("contact_name")).setText("Mira updated");a.onBackPressed();provider.release.countDown();settle(a);ContactDraft.Value draft=ContactDraft.read(c);assertEquals("Mira updated",draft.person.name);assertEquals(42,draft.person.raw);click(a,"Continue draft");click(a,"save");settle(a);assertEquals(1,provider.rawInserts);assertNull(ContactDraft.read(c));assertEquals("Mira updated",provider.name);}finally{provider.release.countDown();controller.pause().stop().destroy();}}

    static final class ContactsFixture extends ContentProvider {
        String name="Ada",token="";int writes,rawInserts;boolean failWrites;java.util.concurrent.CountDownLatch entered,release;
        public boolean onCreate(){return true;}
        public Cursor query(Uri uri,String[] columns,String selection,String[] args,String order){MatrixCursor rows=new MatrixCursor(columns);
            if(columns.length==2&&"display_name".equals(columns[1])){if(args==null||name.toLowerCase().contains(args[0].replace("%","").toLowerCase()))rows.addRow(new Object[]{7,name});}
            else if(columns.length==3){rows.addRow(new Object[]{42,ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE,name});rows.addRow(new Object[]{42,ContactsContract.CommonDataKinds.Phone.CONTENT_ITEM_TYPE,"+49 30 5550100"});rows.addRow(new Object[]{42,ContactsContract.CommonDataKinds.Email.CONTENT_ITEM_TYPE,"ada@example.test"});}
            else if(columns.length==1&&"raw_contact_id".equals(columns[0])){if(args!=null&&args.length>1&&token.equals(args[1])&&!token.isEmpty())rows.addRow(new Object[]{42});}
            else if(columns.length==1&&args!=null&&args.length>1)rows.addRow(new Object[]{ContactsContract.CommonDataKinds.StructuredName.CONTENT_ITEM_TYPE.equals(args[1])?100:101});return rows;}
        public Uri insert(Uri uri,ContentValues value){if(entered!=null){entered.countDown();try{if(!release.await(5,TimeUnit.SECONDS))throw new IllegalStateException("Fixture timed out");}catch(InterruptedException error){Thread.currentThread().interrupt();throw new IllegalStateException(error);}}if(failWrites)throw new IllegalStateException("Fixture write denied");writes++;if(uri.getPath().contains("raw_contacts"))rawInserts++;if("vnd.android.cursor.item/vnd.org.textphone.save".equals(value.getAsString("mimetype")))token=value.getAsString("data1");return uri.buildUpon().appendPath("42").build();}
        public int update(Uri uri,ContentValues value,String selection,String[] args){if(failWrites)throw new IllegalStateException("Fixture write denied");writes++;if(args!=null&&"100".equals(args[0]))name=value.getAsString("data1");return 1;}
        public int delete(Uri uri,String selection,String[] args){return 1;}public String getType(Uri uri){return "vnd.android.cursor.item";}
    }
}
