package org.textphone.launcher;

import static org.junit.Assert.*;
import android.app.AlarmManager;
import android.app.Service;
import android.content.Context;
import android.content.Intent;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.robolectric.Robolectric;
import org.robolectric.RobolectricTestRunner;
import org.robolectric.RuntimeEnvironment;
import org.robolectric.Shadows;
import org.robolectric.annotation.Config;
import org.robolectric.android.controller.ServiceController;
import org.robolectric.shadows.ShadowAlarmManager;

@RunWith(RobolectricTestRunner.class)
@Config(sdk={23,35})
public class TaskReminderFlowTest {
    private Context context;private PlannerStore planner;
    @Before public void clear(){context=RuntimeEnvironment.getApplication();context.getSharedPreferences("pocket_planner",0).edit().clear().commit();context.getSharedPreferences("pocket_agenda",0).edit().clear().commit();ClockStore.prefs(context).edit().clear().commit();ShadowAlarmManager.setCanScheduleExactAlarms(true);planner=new PlannerStore(context.getSharedPreferences("pocket_planner",0));}
    @Test public void editingATimeUsesTheSameAlarmAndCompletingCancelsIt(){long task=planner.save(0,"task","Call Mira"),first=System.currentTimeMillis()+600000;TaskReminders.set(context,task,first);long alarm=TaskReminders.find(context,task).id;TaskReminders.set(context,task,first+600000);assertEquals(alarm,TaskReminders.find(context,task).id);assertEquals(1,ClockStore.entries(context).size());assertEquals(1,Shadows.shadowOf(context.getSystemService(AlarmManager.class)).getScheduledAlarms().size());TaskReminders.toggle(context,task);assertTrue(planner.find(task).done);assertNull(TaskReminders.find(context,task));assertTrue(Shadows.shadowOf(context.getSystemService(AlarmManager.class)).getScheduledAlarms().isEmpty());TaskReminders.toggle(context,task);assertFalse(planner.find(task).done);assertNull(TaskReminders.find(context,task));}
    @Test public void completionClearsLinkedAppointmentRemindersWithoutDeletingTheAppointment(){long task=planner.save(0,"task","Prepare meeting");ClockStore.Entry alarm=new ClockStore.Entry();alarm.kind="reminder";alarm.title="Meeting";alarm.due=System.currentTimeMillis()+600000;alarm.enabled=true;AlarmScheduler.saveAndArm(context,alarm);AgendaStore.Event appointment=new AgendaStore.Event();appointment.title="Meeting";appointment.when=alarm.due;appointment.task=task;appointment.alarm=alarm.id;AgendaStore.save(context,appointment);TaskReminders.toggle(context,task);assertEquals("Meeting",AgendaStore.find(context,appointment.id).title);assertEquals(0,AgendaStore.find(context,appointment.id).alarm);assertNull(ClockStore.find(context,alarm.id));}
    @Test public void editingTitleUpdatesTheReminderAndDeleteCannotLeaveAnAlert(){long task=planner.save(0,"task","Original");TaskReminders.set(context,task,System.currentTimeMillis()+600000);long due=TaskReminders.find(context,task).due;planner.save(task,"task","Revised");TaskReminders.rename(context,task,"Revised");assertEquals("Revised",TaskReminders.find(context,task).title);assertEquals(due,TaskReminders.find(context,task).due);TaskReminders.delete(context,task);assertNull(planner.find(task));assertTrue(ClockStore.entries(context).isEmpty());}
    @Test public void snoozeKeepsTheTaskLinkAndCompletionBlocksALateSnooze(){long task=planner.save(0,"task","Review"),when=System.currentTimeMillis()+600000;TaskReminders.set(context,task,when);ClockStore.Entry e=TaskReminders.find(context,task);ServiceController<AlarmService> c=Robolectric.buildService(AlarmService.class).create();try{AlarmService service=c.get();Intent ring=new Intent().putExtra("id",e.id).putExtra("occurrence",when).putExtra("task",task).putExtra("title","Review");assertEquals(Service.START_STICKY,service.onStartCommand(ring,0,1));Intent snooze=new Intent().setAction("SNOOZE").putExtra("id",e.id).putExtra("occurrence",when);service.onStartCommand(snooze,0,2);ClockStore.Entry later=TaskReminders.find(context,task);assertNotNull(later);assertEquals(e.id,later.id);assertEquals(task,later.task);assertTrue(later.due>System.currentTimeMillis());service.onStartCommand(new Intent().putExtra("id",later.id).putExtra("occurrence",later.due).putExtra("task",task).putExtra("title",later.title),0,3);TaskReminders.toggle(context,task);service.onStartCommand(new Intent().setAction("SNOOZE").putExtra("id",later.id).putExtra("occurrence",later.due),0,4);assertTrue(ClockStore.entries(context).isEmpty());}finally{c.destroy();}}
    @Test public void aQueuedDeliveryAfterCompletionCannotStartRinging(){long task=planner.save(0,"task","Finished"),due=System.currentTimeMillis()+600000;TaskReminders.set(context,task,due);ClockStore.Entry e=TaskReminders.find(context,task);TaskReminders.toggle(context,task);ServiceController<AlarmService> c=Robolectric.buildService(AlarmService.class).create();try{assertEquals(Service.START_NOT_STICKY,c.get().onStartCommand(new Intent().putExtra("id",e.id).putExtra("occurrence",due).putExtra("task",task).putExtra("title","Finished"),0,1));assertFalse(ClockStore.prefs(context).contains("active_started"));}finally{c.destroy();}}
    @Test public void aCompletedTaskCannotAcquireANewReminder(){long task=planner.save(0,"task","Done");TaskReminders.toggle(context,task);try{TaskReminders.set(context,task,System.currentTimeMillis()+600000);fail();}catch(IllegalStateException expected){assertTrue(expected.getMessage().contains("completed"));}assertTrue(ClockStore.entries(context).isEmpty());}
    @Test public void aPausedFutureReminderIsLabelledOff(){long task=planner.save(0,"task","Call Mira");TaskReminders.set(context,task,System.currentTimeMillis()+600000);ClockStore.Entry e=TaskReminders.find(context,task);e.enabled=false;ClockStore.save(context,e);AlarmScheduler.cancel(context,e.id);assertTrue(TaskReminders.label(context,task).startsWith("Reminder off"));}
    @Test public void clockCannotRearmAnOrphanedReminderForACompletedTask(){long task=planner.save(0,"task","Finished");TaskReminders.set(context,task,System.currentTimeMillis()+600000);ClockStore.Entry e=TaskReminders.find(context,task);e.enabled=false;ClockStore.save(context,e);AlarmScheduler.cancel(context,e.id);planner.toggle(task);if(android.os.Build.VERSION.SDK_INT>=33)Shadows.shadowOf(RuntimeEnvironment.getApplication()).grantPermissions(android.Manifest.permission.POST_NOTIFICATIONS);org.robolectric.android.controller.ActivityController<ClockActivity> c=Robolectric.buildActivity(ClockActivity.class).setup();try{PocketAppsTest.find(c.get().body,"resume / on").performClick();assertNotNull(CameraAlbumTest.findContaining(c.get().findViewById(android.R.id.content),"completed or removed"));assertTrue(Shadows.shadowOf(context.getSystemService(AlarmManager.class)).getScheduledAlarms().isEmpty());assertFalse(ClockStore.find(context,e.id).enabled);}finally{c.pause().stop().destroy();}}
}
