// Draws every loading sprite and writes the same frames for the browser and the phone.
//   node tools/sprites/build.mjs [--sheet]      (--sheet also writes contact sheets to %TEMP%/shots)
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { encode, N } from './lib.mjs';
import { PIP, PIP_ORDER } from './pip.mjs';
import { CART } from './cart.mjs';
import { COIN } from './coin.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const rle = list => list.map(encode);
const data = { pip: PIP_ORDER.map(name => rle(PIP[name])), cart: rle(CART), coin: rle(COIN) };
const bytes = JSON.stringify(data).length;

const js = `// Generated by tools/sprites/build.mjs. Do not edit by hand.
// ${N}×${N} frames, run-length encoded as <count><letter>; letters are tinted from the accent colour (see sprite-player.js).
export const SPRITE_SIZE = ${N};
export const PIP_ORDER = ${JSON.stringify(PIP_ORDER)};
export const PIP = ${JSON.stringify(data.pip)};
export const CART = ${JSON.stringify(data.cart)};
export const COIN = ${JSON.stringify(data.coin)};
`;
fs.writeFileSync(path.join(root, 'src/shared/sprites.js'), js);

const jstr = value => '"' + value + '"';
const jlist = list => '{' + list.map(jstr).join(',\n        ') + '}';
const java = `package org.textphone.launcher;

/** Generated by tools/sprites/build.mjs. Do not edit by hand. Same frames as src/shared/sprites.js. */
final class RetroSprites {
    static final int SIZE = ${N};
    /** pip activities in this order: ${PIP_ORDER.join(', ')} */
    static final String[][] PIP = {
${data.pip.map(frames => '        ' + jlist(frames)).join(',\n')}
    };
    static final String[] CART = ${jlist(data.cart)};
    static final String[] COIN = ${jlist(data.coin)};
    private RetroSprites() { }
}
`;
fs.writeFileSync(path.join(root, 'app/src/main/java/org/textphone/launcher/RetroSprites.java'), java);
console.log(`wrote ${PIP_ORDER.reduce((n, name) => n + PIP[name].length, 0)} pip + ${CART.length} cartridge + ${COIN.length} coin frames, ${(bytes / 1024).toFixed(0)} KB of data`);

if (process.argv.includes('--sheet')) {
  const { sheet } = await import('./preview.mjs');
  const out = path.join(process.env.TEMP || '.', 'shots') + path.sep;
  sheet(out + 'sprites-pip.png', PIP_ORDER.flatMap(name => PIP[name]), { cols: 8, scale: 3 });
  sheet(out + 'sprites-props.png', [...CART, ...COIN], { cols: 7, scale: 3 });
}
