// Generated by tools/sprites/ps1/build.mjs. Do not edit by hand.
// pip is a low-poly PS1-style render; the sync loader is a PS2-style memory-card screen. Sheets live in /sprites/<kind>-<accent>.png.
export const SPRITE_SIZE = 96;
export const PIP_ORDER = ["wave","walk","juggle","read","hop","write","pull"];
export const PIP_FRAMES = [12,16,12,12,12,12,4];
export const PIP_STEP_MS = [95,85,80,110,85,100,90];
export const PIP_COLS = 16;
export const SAVE_FRAMES = 32, SAVE_COLS = 8, SAVE_STEP_MS = 60;
export const ACCENTS = {"yellow":"#f9f594","green":"#9be564","blue":"#8fdde7","white":"#ffffff"};
