package org.textphone.launcher;

/** Generated by tools/sprites/ps1/build.mjs. Do not edit by hand. Same sheets and timing as src/shared/sprites.js. */
final class RetroSprites {
    static final int SIZE = 96, PIP_COLS = 16, SAVE_FRAMES = 32, SAVE_COLS = 8, SAVE_STEP_MS = 60;
    /** pip activities: wave, walk, juggle, read, hop, write, pull */
    static final int[] PIP_FRAMES = {12, 16, 12, 12, 12, 12, 4};
    static final int[] PIP_STEP_MS = {95, 85, 80, 110, 85, 100, 90};
    static final String[] ACCENT_NAMES = {"yellow", "green", "blue", "white"};
    static final int[] ACCENT_COLORS = {0xFFF9F594, 0xFF9BE564, 0xFF8FDDE7, 0xFFFFFFFF};
    private RetroSprites() { }
}
