// Renders pip (PS1) and the save-screen loader (PS2) for each accent colour, and writes the same sprite sheets
// for the phone (app/src/main/assets/sprites) and the browser (public/sprites), plus a small shared manifest.
//   node tools/sprites/ps1/build.mjs
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { renderPip, ANIMATIONS, STEP_MS } from './pip3d.mjs';
import { saveFrame, SAVE_FRAMES } from './savescreen.mjs';
import { png } from './apng.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../../..');
const SIZE = 96, ORDER = ['wave', 'walk', 'juggle', 'read', 'hop', 'write', 'pull'], COLS = 16, SAVE_COLS = 8, SAVE_MS = 60;
// Settings → accent on the phone; the browser follows the same synced choice.
const ACCENTS = { yellow: 0xf9f594, green: 0x9be564, blue: 0x8fdde7, white: 0xffffff };
const rgb = hex => [(hex >> 16 & 255) / 255, (hex >> 8 & 255) / 255, (hex & 255) / 255];

function pack(frames, cols) {
  const rows = Math.ceil(frames.length / cols), W = cols * SIZE, H = rows * SIZE, out = new Uint8ClampedArray(W * H * 4);
  frames.forEach((f, i) => { if (!f) return; const ox = (i % cols) * SIZE, oy = Math.floor(i / cols) * SIZE; for (let y = 0; y < SIZE; y++) out.set(f.subarray(y * SIZE * 4, (y + 1) * SIZE * 4), ((oy + y) * W + ox) * 4); });
  return { W, H, out };
}
const dirs = [path.join(root, 'public/sprites'), path.join(root, 'app/src/main/assets/sprites')];
for (const dir of dirs) fs.mkdirSync(dir, { recursive: true });
let bytes = 0;
for (const [name, hex] of Object.entries(ACCENTS)) {
  const accent = rgb(hex), frames = [];
  for (const activity of ORDER) { const list = ANIMATIONS[activity]; for (let i = 0; i < COLS; i++) frames.push(i < list.length ? renderPip(list[i], { accent }) : null); }
  const pip = pack(frames, COLS), save = pack([...Array(SAVE_FRAMES)].map((_, i) => saveFrame(i, SAVE_FRAMES, { accent })), SAVE_COLS);
  for (const dir of dirs) { png(path.join(dir, `pip-${name}.png`), pip.W, pip.H, pip.out); png(path.join(dir, `save-${name}.png`), save.W, save.H, save.out); }
  bytes += fs.statSync(path.join(dirs[0], `pip-${name}.png`)).size + fs.statSync(path.join(dirs[0], `save-${name}.png`)).size;
}
const frames = ORDER.map(a => ANIMATIONS[a].length), steps = ORDER.map(a => STEP_MS[a]);
fs.writeFileSync(path.join(root, 'src/shared/sprites.js'), `// Generated by tools/sprites/ps1/build.mjs. Do not edit by hand.
// pip is a low-poly PS1-style render; the sync loader is a PS2-style memory-card screen. Sheets live in /sprites/<kind>-<accent>.png.
export const SPRITE_SIZE = ${SIZE};
export const PIP_ORDER = ${JSON.stringify(ORDER)};
export const PIP_FRAMES = ${JSON.stringify(frames)};
export const PIP_STEP_MS = ${JSON.stringify(steps)};
export const PIP_COLS = ${COLS};
export const SAVE_FRAMES = ${SAVE_FRAMES}, SAVE_COLS = ${SAVE_COLS}, SAVE_STEP_MS = ${SAVE_MS};
export const ACCENTS = ${JSON.stringify(Object.fromEntries(Object.entries(ACCENTS).map(([k, v]) => [k, '#' + v.toString(16).padStart(6, '0')])))};
`);
fs.writeFileSync(path.join(root, 'app/src/main/java/org/textphone/launcher/RetroSprites.java'), `package org.textphone.launcher;

/** Generated by tools/sprites/ps1/build.mjs. Do not edit by hand. Same sheets and timing as src/shared/sprites.js. */
final class RetroSprites {
    static final int SIZE = ${SIZE}, PIP_COLS = ${COLS}, SAVE_FRAMES = ${SAVE_FRAMES}, SAVE_COLS = ${SAVE_COLS}, SAVE_STEP_MS = ${SAVE_MS};
    /** pip activities: ${ORDER.join(', ')} */
    static final int[] PIP_FRAMES = {${frames.join(', ')}};
    static final int[] PIP_STEP_MS = {${steps.join(', ')}};
    static final String[] ACCENT_NAMES = {${Object.keys(ACCENTS).map(k => '"' + k + '"').join(', ')}};
    static final int[] ACCENT_COLORS = {${Object.values(ACCENTS).map(v => '0xFF' + v.toString(16).padStart(6, '0').toUpperCase()).join(', ')}};
    private RetroSprites() { }
}
`);
console.log(`wrote ${frames.reduce((a, b) => a + b, 0)} pip + ${SAVE_FRAMES} save frames for ${Object.keys(ACCENTS).length} accents, ${(bytes / 1024).toFixed(0)} KB per platform`);
